### PR TITLE
Add dependencies

### PR DESCRIPTION
**Pull request by maethor**
This PR adds a dependency between all "mysql" services and "Mysql-connection".

### CODE REVIEW

**Comment by olivierHa** [comment]
typo : "service_dependencies  ,Mysql-connection"

Your PR includes  a "debug" commit

**Comment by maethor** [comment]
The comma is not a typo. The right syntax of service_dependencies is "host,service", but we can leave the "host" part empty to refer the current host. My PR have been tested and works perfectly.

Sorry about the Debug commit, I just squashed the branch.

**Comment by olivierHa** [comment]
Oh great !

**Comment by maethor** [comment]
Thanks

**Pull request merged**
